package com.engefour.jeraswapi.model

import java.util.*

data class FilmResult(val result: List<Film>)

data class  Film( val title:String,
                  val episodeId:Int,
                  val openingCrawl:String,
                  val director:String,
                  val producer:String,
                  val releaseDate:Date,
                  val species: List<Specie>,
                  val starships: List<Starship>,
                  val vehicles: List<Vehicle>,
                  val characters: List<Person>,
                  val planets: List<Planet>,
                  val hyperMediaUrl: String,
                  val creationDate: String,
                  val editedDate: String)

data class  Specie( val name:String,
                    val classification:String,
                    val designation:String,
                    val averageHeight:String,
                    val averageLifespan:String,
                    val eyeColors: String,
                    val hairColors: String,
                    val skinColors: String,
                    val language: String,
                    val homeworld: String,
                    val peopleUrls: List<Person>,
                    val filmsUrls: List<Film>,
                    val hyperMediaUrl: String,
                    val creationDate: String,
                    val editedDate: String)

data class  Starship( val name:String,
                      val model: String,
                      val manufacturer: String,
                      val costInCredits: String,
                      val length:String,
                      val crew: String,
                      val passengers: String,
                      val maxAtmospheringSpeed: String,
                      val hyperdriveRating: String,
                      val mglt: String,
                      val cargoCapacity: String,
                      val consumables: String,
                      val filmsUrls: List<Film>,
                      val pilotsUrls: List<Person>,
                      val hyperMediaUrl: String,
                      val creationDate: String,
                      val editedDate: String)

data class  Vehicle( val name:String,
                     val model:String,
                     val vehicleClass:String,
                     val manufacturer:String,
                     val length:String,
                     val costInCredits:String,
                     val crew: String,
                     val passengers: String,
                     val maxAtmospheringSpeed: String,
                     val cargoCapacity: String,
                     val consumables: String,
                     val filmsUrls: List<Film>,
                     val pilotsUrls: List<Person>,
                     val hyperMediaUrl: String,
                     val creationDate: String,
                     val editedDate: String)

data class  Person( val name:String,
                    val birthYear:String,
                    val eyeColor:String,
                    val gender:String,
                    val hairColor: String,
                    val height: String,
                    val mass: String,
                    val skinColor: String,
                    val homeworld: String,
                    val filmsUrls: List<String>,
                    val speciesUrls: List<Specie>,
                    val starshipsUrls: List<Starship>,
                    val vehiclesUrls: List<Vehicle>,
                    val hyperMediaUrl: String,
                    val creationDate: String,
                    val editedDate: String)

data class  Planet( val name:String,
                    val diameter:String,
                    val rotationPeriod:String,
                    val orbitalPeriod:String,
                    val gravity:String,
                    val population: String,
                    val climate: String,
                    val terrain: String,
                    val surfaceWater: String,
                    val residents: List<Person>,
                    val films: List<Film>,
                    val hyperMediaUrl: String,
                    val creationDate: String,
                    val editedDate: String)
